name: Doxygen Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.8

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html
          token: ${{ secrets.TOKEN_TEST_GH_PAGES }}
          repository-name: katono/test_gh_pages
          branch: gh_pages
