name: Doxygen Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.8

      - name: Create .nojekyll
        run: |
          pwd
          echo ${{github.workspace}}
          ls -la
          echo ls -la html
          ls -la html
          cp -r html html_new
          echo ls -la html_new
          ls -la html_new
          touch html_new/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html_new
          token: ${{ secrets.TOKEN_TEST_GH_PAGES }}
          repository-name: katono/test_gh_pages
          branch: master
